name: Automated tests for Continuous Integration
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Create runtime path"
        run:  mkdir runtime
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4.1.1
        with:
          path: runtime/vim-vlsim
      - name: "Checkout Vim-Unittest"
        uses: actions/checkout@v4.1.1
        with:
          repository: laurentalacoque/vim-unittest
          path: runtime/vim-unittest
      - name: "Install vim"
        run: sudo apt-get install vim
      - name: "Install Pathogen"
        run: mkdir -p ~/.vim ~/.vim/autoload && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim && echo "execute pathogen#infect()" > ~/.vimrc
      - name: "Link to runtime from vim/bundle"
        run: ln -s $GITHUB_WORKSPACE/runtime/ ~/.vim/bundle && ls -l ~/.vim/bundle && ls -l ~/.vim/bundle/vim-unittest && cat ~/.vimrc
      - name: "FileTypes Verilog"
        run: echo "au BufNewFile,BufRead *.v set ft=verilog" >> ~/.vimrc
      - name: "FileTypes VHDL"
        run: echo "au BufNewFile,BufRead *.vhd set ft=vhdl" >> ~/.vimrc
      - name: "Filetypes SystemVerilog"
        run: echo "au BufNewFile,BufRead *.sv set ft=systemverilog" >> ~/.vimrc
      - name: "Syntax & FileTypes on"
        run: echo "syntax on" >> ~/.vimrc && echo "filetype plugin indent on" >> ~/.vimrc
      - name: "UnitTests CORE"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_core_functions.vim
      - name: "UnitTests CTAGS v/sv"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_v_sv.vim
      - name: "UnitTests CTAGS vhd"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_vhd.vim
