name: Automated tests for Continuous Integration
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Create runtime path"
        run:  mkdir runtime
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4.1.1
        with:
          path: runtime/vim-vlsim
      - name: "Checkout Vim-Unittest"
        uses: actions/checkout@v4.1.1
        with:
          repository: laurentalacoque/vim-unittest
          path: runtime/vim-unittest
      - name: "Install vim and dependencies"
        run: sudo apt-get install vim && sh $GITHUB_WORKSPACE/runtime/vim-vlsim/.github/ressources/setup_minimal_vim.sh
      - name: "UnitTests CORE"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_core_functions.vim
      - name: "UnitTests CTAGS v/sv"
        if: always()
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_v_sv.vim
      - name: "UnitTests CTAGS vhd"
        if: always()
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_vhd.vim
      - name: "UnitTests YANK vhd"
        if: always()
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_yank_vhd.vim
      - name: "UnitTests YANK v"
        if: always()
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_yank_v.vim
      - name: "UnitTests YANK sv"
        if: always()
        run: timeout -k 1 -s INT 60 runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_yank_sv.vim
      - name: "UnitTests PASTE"
        if: always()
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_paste.vim
