name: Automated tests for Continuous Integration
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: "Create runtime path"
        run:  mkdir runtime
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4.1.1
        with:
          path: runtime/vim-vlsim
      - name: "Checkout Vim-Unittest"
        uses: actions/checkout@v4.1.1
        with:
          repository: laurentalacoque/vim-unittest
          path: runtime/vim-unittest
      - name: "Install vim and dependencies"
        run: sudo apt-get install vim && sh $GITHUB_WORKSPACE/runtime/vim-vlsim/.github/ressources/setup_minimal_vim.sh
      - name: "UnitTests CORE"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_core_functions.vim
        continue-on-error: true
      - name: "UnitTests CTAGS v/sv"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_v_sv.vim
        continue-on-error: true
      - name: "UnitTests CTAGS vhd"
        run: runtime/vim-unittest/bin/vunit -c none runtime/vim-vlsim/test/test_ctags_vhd.vim
        continue-on-error: true
